- hosts: kubermaster
  become: yes
  tasks:
    - name: Copy cgroupDriver to host
      copy:
        src: /etc/ansible/files/kubeadm-config.yaml
        dest: $HOME/kubeadm-config.yaml

    - name: Init the cluster
      shell: kubeadm init --config kubeadm-config.yaml >> kubeinit.txt
      args:
        chdir: $HOME
        creates: kubeinit.txt

    - name: Kubernetes profile directory
      become: yes
      become_user: user
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Update userconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/user/.kube/config
        remote_src: yes
        owner: user

    - name: Install Calico network
      become: yes
      become_user: user
      shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
