- hosts: kubermaster
  become: yes
  tasks:
    - name: Create user "devops"
      user:
        name: "devops"
        password: "devops123"
        state: present
        system: yes
        create_home: devops
        shell: /bin/bash
        groups: sudo

    - name: Init the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> kubeinit.txt
      args:
        chdir: $HOME
        creates: kubeinit.txt

    - name: Kubernetes profile directory
      become: yes
      become_user: devops
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Update userconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: devops

    - name: Install Flannel network
      become: yes
      become_user: devops
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
