- hosts: kubernodes
  become: yes
  tasks:
    - fail: msg="OS should be Debian 10.1, not {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ansible_distribution != 'Debian' or ansible_distribution_version != '10.1'

    - name : Update Debian 10
      apt:
        force: yes
        force_apt_get: yes
        update_cache: yes


    - name : Reboot and wait come up
      reboot:

    - name : Install Repo over https
      apt:
        name :
        - "ca-certificates"
        - "curl"
        - "gnupg"
        - "lsb-release"
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url    : https://download.docker.com/linux/debian/gpg
        state  : present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker's apt repository
      apt_repository:
        repo        : "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable"
        filename    : "docker"
        update_cache: true

    - name: Install Docker
      apt:
        name:
        - "docker-ce=5:19.03.*"
        - "docker-ce-cli=5:19.03.*"
        - "containerd.io"
        state: present
        force: yes
        dpkg_options: force-downgrade
        update_cache: true

    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Update sysctl sets for Kubernetes networking
      shell: |
        cat >>/etc/sysctl.d/kubernetes.conf<<EOF
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        EOF
        sysctl --system

    - name: Add Kubernetes GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
        filename: "kubernetes"
        update_cache: true

    - name: Install Kubernetes components
      apt:
        name:
        - "kubeadm=1.23.1"
        - "kubelet=1.23.1"
        - "kubectl=1.23.1"
        state: present
        force: yes
        dpkg_options: force-downgrade
        update_cache: true
