- hosts: kubermaster
  become: yes
  tasks:
    - name: Copy cgroupDriver to host
      copy:
        src: kubeadm-config.yaml
        dest: $HOME/kubeadm-config.yaml

    - name: Init the cluster
      shell: kubeadm init --config kubeadm-config.yaml --pod-network-cidr=10.244.0.0/16 >> kubeinit.txt
      args:
        chdir: $HOME
        creates: kubeinit.txt

    - name: Kubernetes profile directory
      become: yes
      become_user: root
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Update userconfig
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root

    - name: Install Flannel network
      become: yes
      become_user: root
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
